export const ALGERIA_WILAYAS = [
  { code: 1, nameFr: "Adrar", nameAr: "أدرار", fee: 1200 },
  { code: 2, nameFr: "Chlef", nameAr: "الشلف", fee: 600 },
  { code: 3, nameFr: "Laghouat", nameAr: "الأغواط", fee: 800 },
  { code: 4, nameFr: "Oum El Bouaghi", nameAr: "أم البواقي", fee: 750 },
  { code: 5, nameFr: "Batna", nameAr: "باتنة", fee: 750 },
  { code: 6, nameFr: "Béjaïa", nameAr: "بجاية", fee: 750 },
  { code: 7, nameFr: "Biskra", nameAr: "بسكرة", fee: 850 },
  { code: 8, nameFr: "Béchar", nameAr: "بشار", fee: 1100 },
  { code: 9, nameFr: "Blida", nameAr: "البليدة", fee: 600 },
  { code: 10, nameFr: "Bouira", nameAr: "البويرة", fee: 650 },
  { code: 11, nameFr: "Tamanrasset", nameAr: "تمنراست", fee: 1400 },
  { code: 12, nameFr: "Tébessa", nameAr: "تبسة", fee: 850 },
  { code: 13, nameFr: "Tlemcen", nameAr: "تلمسان", fee: 650 },
  { code: 14, nameFr: "Tiaret (Siège Dari Belle)", nameAr: "تيارت (المقر الرئيسي)", fee: 350 },
  { code: 15, nameFr: "Tizi Ouzou", nameAr: "تيزي وزو", fee: 700 },
  { code: 16, nameFr: "Alger", nameAr: "الجزائر العاصمة", fee: 600 },
  { code: 17, nameFr: "Djelfa", nameAr: "الجلفة", fee: 700 },
  { code: 18, nameFr: "Jijel", nameAr: "جيجل", fee: 750 },
  { code: 19, nameFr: "Sétif", nameAr: "سطيف", fee: 700 },
  { code: 20, nameFr: "Saïda", nameAr: "سعيدة", fee: 550 },
  { code: 21, nameFr: "Skikda", nameAr: "سكيكدة", fee: 750 },
  { code: 22, nameFr: "Sidi Bel Abbès", nameAr: "سيدي بلعباس", fee: 600 },
  { code: 23, nameFr: "Annaba", nameAr: "عنابة", fee: 800 },
  { code: 24, nameFr: "Guelma", nameAr: "قالمة", fee: 800 },
  { code: 25, nameFr: "Constantine", nameAr: "قسنطينة", fee: 750 },
  { code: 26, nameFr: "Médéa", nameAr: "المدية", fee: 650 },
  { code: 27, nameFr: "Mostaganem", nameAr: "مستغانم", fee: 600 },
  { code: 28, nameFr: "M'Sila", nameAr: "المسيلة", fee: 700 },
  { code: 29, nameFr: "Mascara", nameAr: "معسكر", fee: 550 },
  { code: 30, nameFr: "Ouargla", nameAr: "ورقلة", fee: 950 },
  { code: 31, nameFr: "Oran", nameAr: "وهران", fee: 600 },
  { code: 32, nameFr: "El Bayadh", nameAr: "البيض", fee: 750 },
  { code: 33, nameFr: "Illizi", nameAr: "إليزي", fee: 1400 },
  { code: 34, nameFr: "Bordj Bou Arréridj", nameAr: "برج بوعريريج", fee: 700 },
  { code: 35, nameFr: "Boumerdès", nameAr: "بومرداس", fee: 650 },
  { code: 36, nameFr: "El Tarf", nameAr: "الطارف", fee: 850 },
  { code: 37, nameFr: "Tindouf", nameAr: "تندوف", fee: 1400 },
  { code: 38, nameFr: "Tissemsilt", nameAr: "تيسمسيلت", fee: 500 },
  { code: 39, nameFr: "El Oued", nameAr: "الوادي", fee: 900 },
  { code: 40, nameFr: "Khenchela", nameAr: "خنشلة", fee: 800 },
  { code: 41, nameFr: "Souk Ahras", nameAr: "سوق أهراس", fee: 850 },
  { code: 42, nameFr: "Tipaza", nameAr: "تيبازة", fee: 650 },
  { code: 43, nameFr: "Mila", nameAr: "ميلة", fee: 750 },
  { code: 44, nameFr: "Aïn Defla", nameAr: "عين الدفلى", fee: 600 },
  { code: 45, nameFr: "Naâma", nameAr: "النعامة", fee: 800 },
  { code: 46, nameFr: "Aïn Témouchent", nameAr: "عين تموشنت", fee: 650 },
  { code: 47, nameFr: "Ghardaïa", nameAr: "غرداية", fee: 900 },
  { code: 48, nameFr: "Relizane", nameAr: "غليزان", fee: 550 },
  { code: 49, nameFr: "Timimoun", nameAr: "تيميمون", fee: 1200 },
  { code: 50, nameFr: "Bordj Badji Mokhtar", nameAr: "برج باجي مختار", fee: 1500 },
  { code: 51, nameFr: "Ouled Djellal", nameAr: "أولاد جلال", fee: 850 },
  { code: 52, nameFr: "Béni Abbès", nameAr: "بني عباس", fee: 1200 },
  { code: 53, nameFr: "In Salah", nameAr: "عين صالح", fee: 1300 },
  { code: 54, nameFr: "In Guezzam", nameAr: "عين قزام", fee: 1500 },
  { code: 55, nameFr: "Touggourt", nameAr: "تقرت", fee: 900 },
  { code: 56, nameFr: "Djanet", nameAr: "جانت", fee: 1400 },
  { code: 57, nameFr: "El M'Ghair", nameAr: "المغير", fee: 900 },
  { code: 58, nameFr: "El Meniaa", nameAr: "المنيعة", fee: 1000 }
];
